### ISSUE TITLE
Won't Install

### ISSUE THREAD

**Issue by mtwb47** [sezanzeb/key-mapper#142]
I'm sure what I'm experiecing is a dependency issue, but I don't know what one.

I've tried to install via the AUR. This was the output.

```
running install
generating translation for it_IT
po/it_IT.po:67: keyword "Predefiniti" unknown
po/it_IT.po:67:23: syntax error
msgfmt: found 2 fatal errors
Traceback (most recent call last):
  File "/home/drmdub/.cache/yay/key-mapper-git/src/key-mapper/setup.py", line 85, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/drmdub/.cache/yay/key-mapper-git/src/key-mapper/setup.py", line 43, in run
    make_lang()
  File "/home/drmdub/.cache/yay/key-mapper-git/src/key-mapper/setup.py", line 73, in make_lang
    subprocess.run(['msgfmt', '-o', join('mo', lang, 'key-mapper.mo'), str(po_file)], check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['msgfmt', '-o', 'mo/it_IT/key-mapper.mo', 'po/it_IT.po']' returned non-zero exit status 1.
==> ERROR: A failure occurred in package().
    Aborting...
error making: key-mapper-git

```
Or most of the output. I copied that after "Entering Fakeroot environment"

(I also did this with paru and had the same problem).

So then I decided to use pip. 

This was the outcome:
  ```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zszlz92x/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zszlz92x/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1_56hw2s/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/key-mapper
         cwd: /tmp/pip-req-build-zszlz92x/
    Complete output (25 lines):
    running install
    generating translation for sk_SK
    generating translation for it_IT
    po/it_IT.po:67: keyword "Predefiniti" unknown
    po/it_IT.po:67:23: syntax error
    msgfmt: found 2 fatal errors
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zszlz92x/setup.py", line 85, in <module>
        setup(
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
 File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-zszlz92x/setup.py", line 43, in run
        make_lang()
      File "/tmp/pip-req-build-zszlz92x/setup.py", line 73, in make_lang
        subprocess.run(['msgfmt', '-o', join('mo', lang, 'key-mapper.mo'), str(po_file)], check=True)
      File "/usr/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['msgfmt', '-o', 'mo/it_IT/key-mapper.mo', 'po/it_IT.po']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zszlz92x/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zszlz92x/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1_56hw2s/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/key-mapper Check the logs for full command output.
```

(sorry it's not formatted well. The copy and paste didn't go well).

I'm going to try running the command in the Readme under the pip instructions, but IDK if that will work either.

Any help would be appreciated.

**Comment by mtwb47** [comment]
When I ran sudo python3 setup.py install from the cloned repo this was the outcome:

```
running install
generating translation for it_IT
po/it_IT.po:67: keyword "Predefiniti" unknown
po/it_IT.po:67:23: syntax error
msgfmt: found 2 fatal errors
Traceback (most recent call last):
  File "/home/drmdub/Downloads/gitthings/key-mapper/setup.py", line 85, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/drmdub/Downloads/gitthings/key-mapper/setup.py", line 43, in run
    make_lang()
  File "/home/drmdub/Downloads/gitthings/key-mapper/setup.py", line 73, in make_lang
    subprocess.run(['msgfmt', '-o', join('mo', lang, 'key-mapper.mo'), str(po_file)], check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['msgfmt', '-o', 'mo/it_IT/key-mapper.mo', 'po/it_IT.po']' returned non-zero exit status 1.
```

**Comment by sezanzeb** [comment]
This has probably been solved now: https://github.com/sezanzeb/key-mapper/pull/143
