### ISSUE TITLE
AUR still broken

### ISSUE THREAD

**Issue by Casul51** [sezanzeb/key-mapper#2]
I've rebuilded package and again got errors:

```

└─(18:17:59 on main)──> key-mapper-service                                                                                                                                                                                                   
Loaded config from "/home/casual/.config/key-mapper/config"
Logging to "/home/casual/.log/key-mapper/log"
0.2.0 key-mapper
Traceback (most recent call last):
  File "/usr/bin/key-mapper-service", line 61, in <module>
    can_read_devices()
  File "/usr/lib/python3.8/site-packages/keymapper/dev/permissions.py", line 37, in can_read_devices
    is_plugdev = USER in grp.getgrnam('plugdev').gr_mem
KeyError: "getgrnam(): name not found: 'plugdev'"

└─(18:18:02 on main)──> key-mapper-gtk                                                                                                                                                                                                   
Gtk-Message: 18:18:05.436: Failed to load module "appmenu-gtk-module"
Loaded config from "/home/casual/.config/key-mapper/config"
0.2.0 key-mapper
WARNING: The daemon "key-mapper-service" is not running, mapping keys only works as long as the window is open.
Traceback (most recent call last):
  File "/usr/bin/key-mapper-gtk", line 59, in <module>
    window = Window()
  File "/usr/lib/python3.8/site-packages/keymapper/gtk/window.py", line 112, in __init__
    permitted, _, is_input, is_plugdev, can_write = can_read_devices()
  File "/usr/lib/python3.8/site-packages/keymapper/dev/permissions.py", line 37, in can_read_devices
    is_plugdev = USER in grp.getgrnam('plugdev').gr_mem
KeyError: "getgrnam(): name not found: 'plugdev'"

```

Doing same thing with 'sudo' - same result.

**Comment by sezanzeb** [comment]
oh that's interesting. the plugdev group doesn't even exist on your system.
- Which distro are you using?
- Please post the output `ls -l /dev/input`

**Comment by Casul51** [comment]
Manjaro with testing update branch

```
ls -l /dev/input                                                                                                                                                                                                        

drwxr-xr-x  2 root root     240 дек  5 11:22 by-id
drwxr-xr-x  2 root root     260 дек  5 11:22 by-path
crw-rw-rw-  1 root input 13, 64 дек  5 11:22 event0
crw-rw-rw-  1 root input 13, 65 дек  5 11:22 event1
crw-rw-rw-  1 root input 13, 74 дек  5 11:22 event10
crw-rw-rw-  1 root input 13, 75 дек  5 11:22 event11
crw-rw-rw-  1 root input 13, 76 дек  5 11:22 event12
crw-rw-rw-+ 1 root input 13, 77 дек  5 11:22 event13
crw-rw-rw-  1 root input 13, 78 дек  5 11:22 event14
crw-rw-rw-  1 root input 13, 79 дек  5 11:22 event15
crw-rw-rw-  1 root input 13, 80 дек  5 11:22 event16
crw-rw-rw-  1 root input 13, 81 дек  5 11:22 event17
crw-rw-rw-  1 root input 13, 82 дек  5 11:22 event18
crw-rw-rw-  1 root input 13, 83 дек  5 11:22 event19
crw-rw-rw-  1 root input 13, 66 дек  5 11:22 event2
crw-rw-rw-  1 root input 13, 67 дек  5 11:22 event3
crw-rw-rw-  1 root input 13, 68 дек  5 11:22 event4
crw-rw-rw-  1 root input 13, 69 дек  5 11:22 event5
crw-rw-rw-  1 root input 13, 70 дек  5 11:22 event6
crw-rw-rw-  1 root input 13, 71 дек  5 11:22 event7
crw-rw-rw-  1 root input 13, 72 дек  5 11:22 event8
crw-rw-rw-  1 root input 13, 73 дек  5 11:22 event9
crw-rw-rw-+ 1 root input 13,  0 дек  5 11:22 js0
crw-rw-rw-  1 root input 13, 63 дек  5 11:22 mice
crw-rw-rw-  1 root input 13, 32 дек  5 11:22 mouse0

```

**Comment by sezanzeb** [comment]
I have changed it to make sure the group in question even exists at all. Please try again and thanks for posting this issue

**Comment by Casul51** [comment]
Yep, now it's working. Also I would suggest add those features:

gamepad:
1) map other axis, since key-mapper doesn't map left stick and triggers (but map right stick)
2) and it's probably not necessary to your program, but manually making deadzone (inner and outer) (my gamepad dumb and triggers working in 0 to 32767 diapason, but should -32767 to 36767 and manjaro settings for unknown reason calibrate all axis and brake sticks :D )

generally: 
3) add "macros help" button since app don't anyhow says that it have this feature
4) add macros on key combination (at example - pressing ALT+1 making weird combo in Mortal Kombat xd)  

But anyway app is great and I really like it! Hope see those features (but I guess some of them really hard to implement))).
