### ISSUE TITLE
key-mapper.service start operation timed out. Terminating.

### ISSUE THREAD

**Issue by actdiux** [sezanzeb/key-mapper#208]
When I start the service it times out.
```
Nov 19 17:57:58 xxxx systemd[1]: key-mapper.service start operation timed out. Terminating.
Nov 19 17:57:58 xxxx systemd[1]: Failed to start Service to inject keycodes without the GUI applicati
-- Subject: Unit key-mapper.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit key-mapper.service has failed.
-- 
```

 I think this is why

```
## /usr/bin/python3 /usr/bin/key-mapper-service
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/keymapper/groups.py", line 346, in run
    device_type = classify(device)
  File "/usr/local/lib/python3.6/site-packages/keymapper/groups.py", line 175, in classify
    if _is_gamepad(capabilities):
  File "/usr/local/lib/python3.6/site-packages/keymapper/groups.py", line 93, in _is_gamepad
    evdev.ecodes.BTN_DPAD_DOWN,
AttributeError: module 'evdev.ecodes' has no attribute 'BTN_DPAD_DOWN'
```

I see the error is in module 'evdev.ecodes' , but I found it trying key-mapper

Linux xxxx 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sezanzeb** [comment]
Might be related to https://github.com/sezanzeb/key-mapper/issues/23, I guess python-evdev didn't compile correctly
