### ISSUE TITLE
Installing from release tarball with setup.py fails - "not a git repository"

### ISSUE THREAD

**Issue by adeadman** [sezanzeb/key-mapper#213]
# Environment
- Centos 7 linux
- Python 3.6.8
- Behind firewall so no internet access is available

# Reproducing
- Download latest release source tarball (1.2.1) and extract
- As per README, `sudo python3 setup.py install`

I would expect it to install normally, but instead I get the following error:
```
/usr/lib/python3.6/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
running install
fatal: not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
error: [Errno 13] Permission denied: 'mo'
```

Downloading the repository as zip also has the same effect, it seems the only way would be to clone it to preserve the git history.

The only workaround seems to be running the following:
```
> git init
> git add .
> git commit -m "Init"
```

**Comment by sezanzeb** [comment]
And after the three git commands `sudo python3 setup.py install` works?

**Comment by sezanzeb** [comment]
please run `ls -lhat` in the extracted tarball before and after the three git commands

**Comment by adeadman** [comment]
```
~/Downloads/key-mapper-1.2.1 > ls -la
total 84
drwxrwsr-x 11 aaron-dead users 4096 Oct 20 22:05 .
drwxrwsr-x 8 aaron-dead users 4096 Nov 26 12:18 ..
drwxrwsr-x 2 aaron-dead users 101 Oct 20 22:05 bin
-rw-rw-r-- 1 aaron-dead users 229 Oct 20 22:05 .coveragerc
drwxrwsr-x 2 aaron-dead users 4096 Oct 20 22:05 data
drwxrwsr-x 2 aaron-dead users 51 Oct 20 22:05 DEBIAN
drwxrwsr-x 3 aaron-dead users 45 Oct 20 22:05 .github
-rw-rw-r-- 1 aaron-dead users 1851 Oct 20 22:05 .gitignore
drwxrwsr-x 5 aaron-dead users 4096 Oct 20 22:05 keymapper
-rw-rw-r-- 1 aaron-dead users 35149 Oct 20 22:05 LICENSE
-rw-rw-r-- 1 aaron-dead users 107 Oct 20 22:05 MANIFEST.in
drwxrwsr-x 2 aaron-dead users 57 Oct 20 22:05 po
-rw-rw-r-- 1 aaron-dead users 419 Oct 20 22:05 .pylintrc
drwxrwsr-x 2 aaron-dead users 4096 Oct 20 22:05 readme
-rw-rw-r-- 1 aaron-dead users 1663 Oct 20 22:05 README.md
drwxrwsr-x 2 aaron-dead users 37 Oct 20 22:05 scripts
-rw-rw-r-- 1 aaron-dead users 4208 Oct 20 22:05 setup.py
drwxrwsr-x 3 aaron-dead users 71 Oct 20 22:05 tests
~/Downloads/key-mapper-1.2.1 > git init
Initialized empty Git repository in /usr/people/aaron-dead/Downloads/key-mapper-1.2.1/.git/
~/Downloads/key-mapper-1.2.1 > git add .
~/Downloads/key-mapper-1.2.1 > git commit -m "Init"
[master (root-commit) f287f4a] Init
109 files changed, 23481 insertions(+)
(...output truncated)
~/Downloads/key-mapper-1.2.1 > ls -la
total 84
drwxrwsr-x 12 aaron-dead users 4096 Nov 26 12:18 .
drwxrwsr-x 8 aaron-dead users 4096 Nov 26 12:18 ..
drwxrwsr-x 2 aaron-dead users 101 Oct 20 22:05 bin
-rw-rw-r-- 1 aaron-dead users 229 Oct 20 22:05 .coveragerc
drwxrwsr-x 2 aaron-dead users 4096 Oct 20 22:05 data
drwxrwsr-x 2 aaron-dead users 51 Oct 20 22:05 DEBIAN
drwxrwsr-x 8 aaron-dead users 155 Nov 26 12:18 .git
drwxrwsr-x 3 aaron-dead users 45 Oct 20 22:05 .github
-rw-rw-r-- 1 aaron-dead users 1851 Oct 20 22:05 .gitignore
drwxrwsr-x 5 aaron-dead users 4096 Oct 20 22:05 keymapper
-rw-rw-r-- 1 aaron-dead users 35149 Oct 20 22:05 LICENSE
-rw-rw-r-- 1 aaron-dead users 107 Oct 20 22:05 MANIFEST.in
drwxrwsr-x 2 aaron-dead users 57 Oct 20 22:05 po
-rw-rw-r-- 1 aaron-dead users 419 Oct 20 22:05 .pylintrc
drwxrwsr-x 2 aaron-dead users 4096 Oct 20 22:05 readme
-rw-rw-r-- 1 aaron-dead users 1663 Oct 20 22:05 README.md
drwxrwsr-x 2 aaron-dead users 37 Oct 20 22:05 scripts
-rw-rw-r-- 1 aaron-dead users 4208 Oct 20 22:05 setup.py
drwxrwsr-x 3 aaron-dead users 71 Oct 20 22:05 tests
```

If I run after I get a separate error:

```
~/Downloads/key-mapper-1.2.1 > sudo python3 setup.py install
[sudo] password for aaron-dead:
/usr/lib/python3.6/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
running install
Failed to save the commit hash: [Errno 13] Permission denied: 'keymapper/commit_hash.py'
error: [Errno 13] Permission denied: 'mo'
```
If I then run `python3 setup.py build` without sudo it works - I suspect the permissions issues are to do with my home directory being mounted on nfs - so I would imagine that for the average user, just initialising the git repository would be sufficient to then build/install.

**Comment by adeadman** [comment]
After extracting to a directory that was root-writeable (not nfs) I was able to run it successfully.

**Comment by sezanzeb** [comment]
ok, great!

are you still running python 3.6 by the way?

**Comment by adeadman** [comment]
Yes, that's what's installed on the system, unfortunately.

I've managed to install it on the system, along with its dependencies, but I've not had much luck trying to run it. Initial attempts to run the service hanged, running it directly with `-d` showed that the default PYTHON_EGG_PATH was pointing to my home directory (even when run with sudo), so I had to update the service template to set that environment variable to `/tmp`. And even after that, when running it I'm getting this:

```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.6/site-packages/keymapper/groups.py", line 346, in run
device_type = classify(device)
File "/usr/local/lib/python3.6/site-packages/keymapper/groups.py", line 175, in classify
if _is_gamepad(capabilities):
File "/usr/local/lib/python3.6/site-packages/keymapper/groups.py", line 93, in _is_gamepad
evdev.ecodes.BTN_DPAD_DOWN,
AttributeError: module 'evdev.ecodes' has no attribute 'BTN_DPAD_DOWN'
```

[The evdev docs](https://python-evdev.readthedocs.io/en/latest/apidoc.html#module-evdev.ecodes) don't mention this constant, so I wonder if this is specific to a certain version (I installed the latest from pypi) or depends on the Linux distribution - as it is wrapping `linux/input.h`.

Thanks for all of your help with it :-)

**Comment by sezanzeb** [comment]
> or depends on the Linux distribution - as it is wrapping linux/input.h.

yes

evdev probably didn't compile correctly. There is usually a python-evdev package available in your distros repository, try that
