### ISSUE TITLE
key-mapper.service fails

### ISSUE THREAD

**Issue by Pete-Smith** [sezanzeb/key-mapper#23]
I'm on Ubuntu 20.10 and I downloaded key-mapper 0.60.

Excited about this program!
```
$ sudo systemctl status key-mapper.service

● key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/lib/systemd/system/key-mapper.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2021-01-10 18:26:57 EST; 13s ago
    Process: 5484 ExecStart=/usr/bin/key-mapper-service (code=exited, status=1/FAILURE)
   Main PID: 5484 (code=exited, status=1/FAILURE)

Jan 10 18:26:57 notebook key-mapper-service[5484]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Jan 10 18:26:57 notebook key-mapper-service[5484]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Jan 10 18:26:57 notebook key-mapper-service[5484]:   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
Jan 10 18:26:57 notebook key-mapper-service[5484]:   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
Jan 10 18:26:57 notebook key-mapper-service[5484]:   File "<frozen zipimport>", line 259, in load_module
Jan 10 18:26:57 notebook key-mapper-service[5484]:   File "/usr/local/lib/python3.8/dist-packages/evdev-1.3.0-py3.8-linux-x86_64.egg/evdev/ecodes.py", line 77, in <module>
Jan 10 18:26:57 notebook key-mapper-service[5484]: NameError: name 'BTN' is not defined
Jan 10 18:26:57 notebook systemd[1]: key-mapper.service: Main process exited, code=exited, status=1/FAILURE
Jan 10 18:26:57 notebook systemd[1]: key-mapper.service: Failed with result 'exit-code'.
Jan 10 18:26:57 notebook systemd[1]: Failed to start Service to inject keycodes without the GUI application.
```

**Comment by Pete-Smith** [comment]
The same NameError occurs when trying to bring up the gui, as well.
```
pfs@notebook ~/s/key-mapper (main)> key-mapper-gtk
Traceback (most recent call last):
  File "/usr/bin/key-mapper-gtk", line 35, in <module>
    from keymapper.gtk.window import Window
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/key_mapper-0.6.0-py3.8.egg/keymapper/gtk/window.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/key_mapper-0.6.0-py3.8.egg/keymapper/state.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/evdev-1.3.0-py3.8-linux-x86_64.egg/evdev/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/evdev-1.3.0-py3.8-linux-x86_64.egg/evdev/device.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/evdev-1.3.0-py3.8-linux-x86_64.egg/evdev/ecodes.py", line 77, in <module>
NameError: name 'BTN' is not defined
```

**Comment by Pete-Smith** [comment]
Sorry. The error isn't in your package, it's in *evdev 1.3.0*.

**Comment by sezanzeb** [comment]
looked into it quickly, there is some weird stuff going on indeed.

lets make it even weirder and try

```python
keys.update(BTN or {})
keys.update(KEY or {})
```
in `"/usr/local/lib/python3.8/dist-packages/evdev-1.3.0-py3.8-linux-x86_64.egg/evdev/ecodes.py", line 77`

And then run

`key-mapper-control --key-names`

(with the latest commit of key-mapper, because that command previously only ran with a running service)

If that works and if there is key_ stuff in there, this can easily be made into a PR for python-evdev

**Comment by Pete-Smith** [comment]
I had installed via setuptools. Removing evdev and reinstalling via pip makes it importable, and key-mapper's interface is able to open, now.

**Comment by sezanzeb** [comment]
ah ok

**Comment by Pete-Smith** [comment]
There must have been some compilation hook that didn't fire via setuptools. Evdev's setup.py is a little crazy. Thanks!

**Comment by xenburn** [comment]
this isn't isolated, I've got the same error. I tried my distros package and then from source. I tried clearing all the files out and tried with a virtualenv as well as trying with pyenv's local shim.

**Comment by sezanzeb** [comment]
Since this error happens in evdev we should move this there

https://github.com/gvalkov/python-evdev/issues/150

**Comment by choc1024** [comment]
@Pete-Smith have you fixed the issue now?

**Comment by sezanzeb** [comment]
For the OSError above, try to install `xf86-input-evdev`, `modprobe uinput` (I don't think this presists across reboots though) and rebooting
