### ISSUE TITLE
Fail to start, installed from AUR

### ISSUE THREAD

**Issue by HellishINC** [sezanzeb/key-mapper#41]
Hey there. Installed from the AUR. Starting the program gives:

```
key-mapper 0.6.1
python-evdev 1.4.0
Creating file "/home/kimoli/.config/key-mapper/config.json"
Traceback (most recent call last):
File "/usr/bin/key-mapper-gtk", line 53, in <module>
from keymapper.gui.window import Window
File "/usr/lib/python3.9/site-packages/keymapper/gui/window.py", line 31, in <module>
from keymapper.state import custom_mapping
File "/usr/lib/python3.9/site-packages/keymapper/state.py", line 32, in <module>
from keymapper.mapping import Mapping, DISABLE_NAME, DISABLE_CODE
File "/usr/lib/python3.9/site-packages/keymapper/mapping.py", line 31, in <module>
from keymapper.config import ConfigBase, config
File "/usr/lib/python3.9/site-packages/keymapper/config.py", line 271, in <module>
config = GlobalConfig()
File "/usr/lib/python3.9/site-packages/keymapper/config.py", line 192, in __init__
self.load_config()
File "/usr/lib/python3.9/site-packages/keymapper/config.py", line 242, in load_config
self.save_config()
File "/usr/lib/python3.9/site-packages/keymapper/config.py", line 262, in save_config
touch(self.path)
File "/usr/lib/python3.9/site-packages/keymapper/paths.py", line 83, in touch
shutil.chown(path, USER, USER)
File "/usr/lib/python3.9/shutil.py", line 1312, in chown
raise LookupError("no such group: {!r}".format(group))
LookupError: no such group: 'kimoli'
```

```
03:02:22 PM   >> $ whoami
kimoli
```

Trying again leads to:
```
key-mapper 0.6.1
python-evdev 1.4.0
ERROR: Failed to parse config "/home/kimoli/.config/key-mapper/config.json": Expecting value: line 1 column 1 (char 0)
```

config.json is an empty file. Deleting it causes the first error, which then goes on to the second error when running again.

**Comment by sezanzeb** [comment]
Hi,

please show me `ls -ld ~`

**Comment by sezanzeb** [comment]
fixes are pushed to main. The file group doesn't matter as long as setting the owner works.

**Comment by HellishINC** [comment]
Hey there, here's the output requested:

```
10:41:20 AM   >> $ ls -ld ~
drwx------ 37 kimoli users 4096 Feb 15 10:32 /home/kimoli
```

key-mapper-gtk now launches. Thanks for the fix. :)
