### ISSUE TITLE
Can't install on pop!_os 20.10

### ISSUE THREAD

**Issue by therealrobster** [sezanzeb/key-mapper#5]
Hi there, trying to install.
I get the following:

```
$ sudo key-mapper-service --setup-permissions
Traceback (most recent call last):
  File "/usr/bin/key-mapper-service", line 38, in <module>
    from keymapper.daemon import Daemon, BUS_NAME
  File "/usr/lib/python3/dist-packages/keymapper/daemon.py", line 34, in <module>
    from keymapper.dev.injector import KeycodeInjector
  File "/usr/lib/python3/dist-packages/keymapper/dev/injector.py", line 31, in <module>
    import evdev
ModuleNotFoundError: No module named 'evdev'
```

If I try and install I get this:
```

$ sudo dpkg -i python3-key-mapper_0.3.1-1_all.deb
(Reading database ... 400745 files and directories currently installed.)
Preparing to unpack python3-key-mapper_0.3.1-1_all.deb ...
Unpacking python3-key-mapper (0.3.1-1) over (0.3.1-1) ...
dpkg: dependency problems prevent configuration of python3-key-mapper:
 python3-key-mapper depends on python3-evdev; however:
  Package python3-evdev is not installed.

dpkg: error processing package python3-key-mapper (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 python3-key-mapper
```
I'm on POP!_OS 20.10

**Comment by sezanzeb** [comment]
```
 python3-key-mapper depends on python3-evdev; however:
  Package python3-evdev is not installed.
```

please try to run `sudo apt-get -f install`

https://askubuntu.com/a/40050

**Comment by therealrobster** [comment]
That totally did it and beyond that, it's completely changed that horror show of dependencies and giving up that I've gone through over the years.  Thank you from many levels :-)
