### ISSUE TITLE
UInputError: uinput device name must not be longer than 80 characters

### ISSUE THREAD

**Issue by mmazur** [sezanzeb/key-mapper#66]
```11.9130 INFO: window.py, line 526, Applying preset "new preset" for "Microsoft Microsoft® 2.4GHz Transceiver v9.0"
11.9132 INFO: config.py, line 246, Loaded config from "/home/mmazur/.config/key-mapper/config.json"
11.9133 INFO: mapping.py, line 162, Loading preset from "/home/mmazur/.config/key-mapper/presets/Microsoft Microsoft® 2.4GHz Transceiver v9.0/new preset.json"
11.9134 SPAM: mapping.py, line 195, Key((1, 58, 1), (1, 11, 1)) maps to home
11.9134 SPAM: mapping.py, line 195, Key((1, 58, 1), (1, 36, 1)) maps to left
11.9175 INFO: injector.py, line 139, Stopping injecting keycodes for device "Microsoft Microsoft® 2.4GHz Transceiver v9.0"
11.9199 DEBUG: numlock.py, line 73, numlockx not found
11.9202 DEBUG: daemon.py, line 437, Using keycodes from "/home/mmazur/.config/key-mapper/xmodmap.json"
11.9220 INFO: pid 360719, injector.py, line 313, Starting injecting the mapping for "Microsoft Microsoft® 2.4GHz Transceiver v9.0"
11.9225 DEBUG: pid 360719, context.py, line 96, Parsing macros
11.9225 DEBUG: pid 360719, context.py, line 108, No macros configured
12.0279 DEBUG: pid 360719, injector.py, line 171, No need to grab /dev/input/event6
12.0283 DEBUG: pid 360719, injector.py, line 158, Grabbing "/dev/input/event5" because of "Key((1, 58, 1), (1, 11, 1))"
12.0285 DEBUG: pid 360719, injector.py, line 182, Grab /dev/input/event5
Process Injector-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/site-packages/keymapper/injection/injector.py", line 351, in run
    forward_to = evdev.UInput(
  File "/usr/local/lib64/python3.8/site-packages/evdev/uinput.py", line 127, in __init__
    self._verify()
  File "/usr/local/lib64/python3.8/site-packages/evdev/uinput.py", line 278, in _verify
    raise UInputError(msg.format(_uinput.maxnamelen))
evdev.uinput.UInputError: uinput device name must not be longer than 80 characters
12.1225 ERROR: injector.py, line 129, Injector was unexpectedly found stopped```

**Comment by sezanzeb** [comment]
pushed a potential fix to main, please try again

**Comment by mmazur** [comment]
Seems it's working now, thx.
