### ISSUE TITLE
python dependencies not found via .deb, Intuos touch buttons

### ISSUE THREAD

**Issue by paranoidfactoid** [sezanzeb/key-mapper#77]
foo@bukowski:\~/Desktop$ key-mapper-gtk -d
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/keymapper/logger.py", line 140, in <module>
    name = pkg_resources.require('key-mapper')[0].project_name
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pydbus' distribution was not found and is required by key-mapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3/dist-packages/keymapper/logger.py", line 98, in format
    debug = is_debug()
NameError: name 'is_debug' is not defined
Call stack:
  File "/usr/bin/key-mapper-gtk", line 37, in <module>
    from keymapper.logger import update_verbosity, log_info
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keymapper/logger.py", line 147, in <module>
    logger.info('Could not figure out the version')
Message: 'Could not figure out the version'
Arguments: ()
20315 0.03236 INFO logger.py:160: key-mapper-gtk  12c9ee6f443e3b454d1f18fc63b553095e549243 https://github.com/sezanzeb/key-mapper
20315 0.03241 INFO logger.py:168: key-mapper-gtk  12c9ee6f443e3b454d1f18fc63b553095e549243 https://github.com/sezanzeb/key-mapper
20315 0.03244 WARNING logger.py:174: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
Traceback (most recent call last):
  File "/usr/bin/key-mapper-gtk", line 53, in <module>
    from keymapper.gui.window import Window
  File "/usr/lib/python3/dist-packages/keymapper/gui/window.py", line 33, in <module>
    from keymapper.state import custom_mapping, system_mapping
  File "/usr/lib/python3/dist-packages/keymapper/state.py", line 29, in <module>
    import evdev
ModuleNotFoundError: No module named 'evdev'

foo@bukowski:\~/Desktop$ apt list | grep pydbus
python-pydbus-doc/focal,focal 0.6.0-2build1 all
python3-pydbus/focal,focal 0.6.0-2build1 all
foo@bukowski:\~/Desktop$

**Comment by paranoidfactoid** [comment]
Note: grabbing the git source and using the build script generated a (seemingly) working .deb. 

Don't know why!

**Comment by paranoidfactoid** [comment]
On a completely separate issue, the app recognizes button presses on my Wacom Intuos 3 and Intuos 4 tablets, it doesn't recognize either the touch sensitive strip on the 3 or the touch sensitive wheel on the 4. Interestingly, Gnome 3.36 system settings does recognize these so its in the system driver and does actually work.

**Comment by sezanzeb** [comment]
Hi,

please run `sudo evtest` and produce the events for the touch-strip on the 3, afterwards share that log

**Comment by jose1711** [comment]
You should really fix the issue title..

**Comment by sezanzeb** [comment]
and what happens if you run

```
python3
import evdev
```

**Comment by sezanzeb** [comment]
checked with the intuos 5 a few days ago, the issue with the touch ring is that it doesn't send a direction, but rather the angle if I remember correctly. So it can only work as a single button in key-mapper.

I need the evtest output of your tablets otherwise I can't do anything

**Comment by sezanzeb** [comment]
Feel free to reopen once you have those logs
